//#include <stdio.h>
//#include <limits.h>
//#include <wchar.h>
//#include <locale.h>
//#include <stdlib.h>
//
//int     ft_printf(const char *format, ...);
//
//int     main(void)
//{
//    double b = 3.9;
//    ft_printf("mine: %f\n", b);
//    printf("ref:: %lf\n", b);
//
//    char    *str;
//
//    setlocale(LC_ALL, "");
//    str = "Hello World!";

//    ft_printf("str: %-20.7s %s c: %c-end-\n", "hello world!", " string2", 'c');
//    printf("ref: %-20.7s %s c: %c-end-\n", "hello world!", " string2", 'c');
//    ft_printf("str: %+-20d-end-\n", INT_MAX);
//    printf("ref: %+-20d-end-\n", INT_MAX);
//    double db = 3.9;
//    ft_printf("mine: %f\n", db);
//    printf("ref:: %lf\n", db);
//    ft_printf("|% 3d|\n", 42);
//    printf("|% 3d|\n", 42);
//    ft_printf("|% 5d|\n", 42);
//    printf("|% 5d|\n", 42);
//    ft_printf("|%+04d|\n", 42);
//    printf("|%+04d|\n", 42);
//    ft_printf("|% 4.5i|\n", 42);
//    printf("|% 4.5i|\n", 42);
//    ft_printf("m: |%4.2i|\n", 42);
//    printf("r: |%4.2i|\n", 42);
//    ft_printf("m: |%4.3i|\n", 42);
//    printf("r: |%4.3i|\n", 42);
//    ft_printf("|% 4.5i|\n", 42);
//   printf("|% 4.5i|\n", 42);
//    ft_printf("|%-5.3d|\n", 42);
//    printf("|%-5.3d|\n", 42);
//    ft_printf("|% 4.5i|\n", 42);
//    printf("|% 4.5i|\n", 42);
//    ft_printf("|% 06.4i|\n", 42);
//    printf("|% 06.4i|\n", 42);
//    ft_printf("|%04.3i|\n", 42);
//    printf("|%04.3i|\n", 42);
//    ft_printf("|% 04.2i|\n", 42);
//    printf("|% 04.2i|\n", 42);
//    ft_printf("|%-5.3s|\n", "LYDI");
//    printf("|%-5.3s|\n", "LYDI");
//    ft_printf("|%04d|\n", 42);
//    printf("|%04d|\n", 42);
//    ft_printf("|%05d|\n", 42);
//    printf("|%05d|\n", 42);
//    ft_printf("|% 4d|\n", 42);
//    printf("|% 4d|\n", 42);
//    ft_printf("|%+04d|\n", 42);
//    printf("|%+04d|\n", 42);
//    ft_printf("|%+04.15d|\n", 42);
//    printf("|%+04.15d|\n", 42);
//    ft_printf("@moulitest: a%5.db a%5.0ib-\n", 0, 0);
//    printf("@moulitest: a%5.db a%5.0ib-\n", 0, 0);
//    ft_printf("@moulitest: a%5.xb a%5.0xb-\n", 10, 10);
//    printf("@moulitest: a%5.xb a%5.0xb-\n", 10, 10);
//    ft_printf("@moulitest: a%5.xb a%5.0xb-\n", 42, 42);
//    printf("@moulitest: a%5.xb a%5.0xb-\n", 42, 42);
//    ft_printf("data: %c\n", 0);
//    printf("data: %c\n", 0);
//    ft_printf("data:%+10.4d-\n", 56);
//    printf("data:%+10.4d-\n", 56);
//    ft_printf("data:%10.4d-\n", 56);
//    printf("data:%10.4d-\n", 56);
//    ft_printf("data:%-10.4d-\n", 56);
//    printf("data:%-10.4d-\n", 56);
//    ft_printf("%-6o-\n", 2500);
//    printf("%-6o-\n", 2500);
//    ft_printf("%-#6o\n", 2500);
//    printf("%-#6o\n", 2500);
//    ft_printf("@moulitest: -%-10.9d-\n", -42);
//    printf("@moulitest: -%-10.9d-\n", -42);
//    char w = 'w';
//    ft_printf("%ld\n", LONG_MAX);
//    printf("%ld\n", LONG_MAX);
//    ft_printf("%hhd\n", w);
//    printf("%hhd\n", w);
//    ft_printf("{%+03d}-\n", 1);
//    printf("{%+03d}-\n", 1);
//    ft_printf("{%+03d}\n", 0);
//    printf("{%+03d}\n", 0);
//    ft_printf("@moulitest: [%.o] [%.0o]--\n", 42, 43);
//    printf("@moulitest: [%.o] [%.0o]--\n", 42, 43);
//    ft_printf("%+10.5d-\n", 4242);
//    printf("%+10.5d-\n", 4242);
//    ft_printf("%0+5d--\n", 42);
//    printf("%0+5d--\n", 42);
//    ft_printf("%-5.10o-\n", 2500);
//    printf("%-5.10o-\n", 2500);
//    ft_printf("@moulitest: %.10d-\n", -42);
//    printf("@moulitest: %.10d-\n", -42);
//    ft_printf("@moulitest: [%5.o] [%5.0o]--\n", 0, 0);
//    printf("@moulitest: [%5.o] [%5.0o]--\n", 0, 0);
//    ft_printf("@moulitest: [%.o] [%.0o]--\n", 42, 43);
//    printf("@moulitest: [%.o] [%.0o]--\n", 42, 43);
//    ft_printf("@moulitest: [%5.o] [%5.0o]--\n", 0, 0);
//    printf("@moulitest: [%5.o] [%5.0o]--\n", 0, 0);
//    ft_printf("@moulitest: %#.o %#.0o-\n", 0, 0);
//    printf("@moulitest: %#.o %#.0o-\n", 0, 0);
//    ft_printf("@moulitest: %.o %.0o-\n", 0, 0);
//    printf("@moulitest: %.o %.0o-\n", 0, 0);
//    char c = 'b';
//
//    ft_printf("%ca\n", 'b');
//    printf("%ca\n", 'b');
//    ft_printf("%7cb\n", c);
//    printf("%7cb\n", c);
//    ft_printf("%-7cc\n", c);
//    printf("%-7cc\n", c);

    // s

//    str = "012345";

//    ft_printf("%sd\n", str);
//    printf("%sd\n", str);
//    ft_printf("%7se\n", str);
//    printf("%7se\n", str);
//    ft_printf("%-7sf\n", str);
//    printf("%-7sf\n", str);
//    ft_printf("%7.2sg\n", str);
//    printf("%7.2sg\n", str);
//    ft_printf("%-7.2sh\n", str);
//    printf("%-7.2sh\n", str);
//    ft_printf("%.2si\n", str);
//    printf("%.2si\n", str);
//    ft_printf("%.7sj\n", str);
//    printf("%.7sj\n", str);
//
//    // p
//    ft_printf("%p\n", str);
//    printf("%p\n", str);
//    ft_printf("%16p\n", str);
//    printf("%16p\n", str);
//    ft_printf("%-15p\n", str);
//    printf("%-15p\n", str);


    // dioux
//    long long x = -23;
//    ft_printf("%.5lld\n", x);
//    printf("%.5lld\n", x);
//    ft_printf("%-.5llda\n", x);
//    printf("%-.5llda\n", x);
//    ft_printf("%+2lldb\n", x);
//    printf("%+2lldb\n", x);
//    ft_printf("%06lldc\n", x);
//    printf("%06lldc\n", x);
//    ft_printf("%-6lldd\n", x);
//    printf("%-6lldd\n", x);
//    ft_printf("%5lldf\n", x);
//    printf("%5lldf\n", x);
//    ft_printf("%-+5.4llde\n", x);
//    printf("%-+5.4llde\n", x);
//    ft_printf("%0+6lldg\n", x);
//    printf("%0+6lldg\n", x);
//    ft_printf("%lldh\n", x);
//    printf("%lldh\n", x);
//    ft_printf("%-7.3lldp\n", x);
//    printf("%-7.3lldp\n", x);
//    ft_printf("% lldpenetration\n", x);
//    printf("% lldpenetration\n", x);
//    ft_printf("% 5.3llddoublepenetration\n", x);
//    printf("% 5.3llddoublepenetration\n", x);

//    unsigned  long long p = 255;
//    ft_printf("%llx\n", p);
//    printf("%llx\n", p);
//    ft_printf("%llX\n", p);
//    printf("%llX\n", p);
//    ft_printf("%llo\n", p);
//    printf("%llo\n", p);
//    ft_printf("%llu\n", p);
//    printf("%llu\n", p);
//
//    unsigned  long long u = 15;
//    ft_printf("%-7.5llxa\n", u);
//    printf("%-7.5llxa\n", u);
//    ft_printf("%07llX\n", u);
//    printf("%07llX\n", u);
//    ft_printf("%0llo\n", u);
//    printf("%0llo\n", u);
//    ft_printf("%#llxe\n", u);
//    printf("%#llxe\n", u);
//    ft_printf("%-#.6llxb\n", u);
//    printf("%-#.6llxb\n", u);
//    ft_printf("%#0.8llxc\n", u);
//    printf("%#0.8llxc\n", u);
//    ft_printf("%#0.8llo\n", u);
//    printf("%#0.8llo\n", u);
//    ft_printf("%#.8llx\n", u);
//    printf("%#.8llx\n", u);
//    ft_printf("%#0.8llo\n", u);
//    printf("%#0.8llo\n", u);
//    ft_printf("%#llo\n", u);
//   printf("%#llo\n", u);
//    ft_printf("%8llx\n", u);
//    printf("%8llx\n", u);
//    ft_printf("%#8llo\n", u);
//    printf("%#8llo\n", u);
//    ft_printf("%#8llx\n", u);
//    printf("%#8llx\n", u);
//    ft_printf("%#8llo\n", u);
//    printf("%#8llo\n", u);

    // f
//    long double i = -234.666669999;
//    ft_printf("%#-.5Lfa\n", i);
//    printf("%#-.5Lfa\n", i);
//    ft_printf("%#+2Lfb\n", i);
//    printf("%#+2Lfb\n", i);
//    ft_printf("%#06Lfc\n", i);
//    printf("%#06Lfc\n", i);
//    ft_printf("%#-6Lfd\n", i);
//    printf("%#-6Lfd\n", i);
//    ft_printf("%#5Lff\n", i);
//    printf("%#5Lff\n", i);
//    ft_printf("%#-+5.4Lfe\n", i);
//    printf("%#-+5.4Lfe\n", i);
//    ft_printf("%#0+6Lfg\n", i);
//    printf("%#0+6Lfg\n", i);
//    ft_printf("%#Lfh\n", i);
//    printf("%#Lfh\n", i);
//    ft_printf("%#-7.3Lfp\n", i);
//    printf("%#-7.3Lfp\n", i);
//    ft_printf("%-.5Lfa\n", i);
//    printf("%-.5Lfa\n", i);
//    ft_printf("%+2Lfb\n", i);
//    printf("%+2Lfb\n", i);
//    ft_printf("%06Lfc\n", i);
//    printf("%06Lfc\n", i);
//    ft_printf("%-6Lfd\n", i);
//    printf("%-6Lfd\n", i);
//    ft_printf("%5Lff\n", i);
//    printf("%5Lff\n", i);
//    ft_printf("%-+5.4Lfe\n", i);
//    printf("%-+5.4Lfe\n", i);
//    ft_printf("%0+6Lfg\n", i);
//    printf("%0+6Lfg\n", i);
//    ft_printf("%Lfh\n", i);
//    printf("%Lfdh\n", i);
//    ft_printf("%-7.3Lfp\n", i);
//    printf("%-7.3Lfp\n", i);
//    ft_printf("% -.3Lfqq\n", i);
//    printf("% -.3Lfqq\n", i);
//    ft_printf("% Lfqqqq\n", i);
//    printf("% Lfqqqq\n", i);
//    ft_printf("%+Lfprincess\n", i);
//    printf("%+Lfprincess\n", i);

//    long double we = .9999999999;
//    ft_printf("%Lf\n", we);
//    printf("%Lf\n", we);
//    long double z = -.99999999999;
//    ft_printf("%Lf\n", z);
//    printf("%Lf\n", z);
//    double ws = .099999999999;
//    ft_printf("%f\n", ws);
//    printf("%f\n", ws);
//    double zs = -.099999999999;
//    ft_printf("%f\n", zs);
//    printf("%f\n", zs);
//    double app = 234009.9999999;
//    ft_printf("%f\n", app);
//    printf("%f\n", app);
//    double app2 = -234009.9999999;
//    ft_printf("%f\n", app2);
//    printf("%f\n", app2);
//    double app3 = -234999.9999999;
//    ft_printf("%f\n", app3);
//    printf("%f\n", app3);
//    double app4 =  234999.9999999;
//    ft_printf("%f\n", app3);
//    printf("%f\n", app3);
//    double torn = 20001300.99999999999;
//    ft_printf("%f\n", torn);
//    printf("%f\n", torn);
//    double torn2 = -20001300.99999999999;
//    ft_printf("%f\n", torn2);
//    printf("%f\n", torn2);
//    double baked = 999999.999999999;
//    ft_printf("%f\n", baked);
//    printf("%f\n", baked);
//    double edibles = 1.9999999999;
//    ft_printf("%f\n", edibles);
//    printf("%f\n", edibles);
//    double edibles2 = -1.9999999999;
//    ft_printf("%f\n", edibles2);
//    printf("%f\n", edibles2);
//    double edibles3 = -123.9999999999;
//    ft_printf("%f\n", edibles3);
//    printf("%f\n", edibles3);
//    double edibles4 = 123.9999999999;
//    ft_printf("%f\n", edibles4);
//    printf("%f\n", edibles4);
//    long double ex = 9223372036854775807;
//    ft_printf("%Lf\n", ex);
//    printf("%Lf\n", ex);
//    long double ex2 = -9223372031114775807;
//    ft_printf("%Lf\n", ex2);
//    printf("%Lf\n", ex2);
//    long double ex3 = 2398437529597300022.9999999;
//    ft_printf("%Lf\n", ex3);
//    printf("%Lf\n", ex3);
//    double dumb = -123.999999;
//    ft_printf("%f\n", dumb);
//    printf("%f\n", dumb);
//    double dumb2 = 123.999999;
//    ft_printf("%f\n", dumb2);
//    printf("%f\n", dumb2);
//    double dumb3 = -123.9999995;
//    ft_printf("%f\n", dumb3);
//    printf("%f\n", dumb3);
//    double dumb4 = 123.9999995;
//    ft_printf("%f\n", dumb4);
//    printf("%f\n", dumb4);
//    double dumb5 = -123.9999996;
//    ft_printf("%f\n", dumb5);
//    printf("%f\n", dumb5);
//    double dumb6  =.9999995;
//    ft_printf("%f\n", dumb6);
//    printf("%f\n", dumb6);
//    double dumb7 = -.9999995;
//    ft_printf("%f\n", dumb7);
//    printf("%f\n", dumb7);
//    double dumb8  =.9999994;
//    ft_printf("%f\n", dumb8);
//    printf("%f\n", dumb8);
//    double dumb9 = -.9999994;
//    ft_printf("%f\n", dumb9);
//    printf("%f\n", dumb9);
//    system("leaks ft_printf");
//}
